#external-igw-1-17-5.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gw-install-external
spec:
  profile: empty
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
  components:
    ingressGateways:
    - name: external-igw-1-17-5
      namespace: external-igw-1-17-5
      enabled: true
      label: 
        gw: external-igw-1-17-5
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: external-igw-1-17-5
          patches:
          - path: spec.template.spec.containers[name:istio-proxy].lifecycle
            value:
               preStop:
                 exec:
                   command: ["sh", "-c", "sleep 5"]
        service:
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
