#partner-igw-1-17-5.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gw-install-partner
spec:
  profile: empty
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
  components:
    ingressGateways:
    - name: partner-igw-1-17-5
      namespace: partner-igw-1-17-5
      enabled: true
      label: 
        gw: partner-igw-1-17-5
      k8s:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: partner-igw-1-17-5
          patches:
          patches:
          - path: spec.template.spec.containers[name:istio-proxy].lifecycle
            value:
               preStop:
                 exec:
                   command: ["sh", "-c", "sleep 5"]
        affinity: 
          nodeAffinity: 
            requiredDuringSchedulingIgnoredDuringExecution: 
              nodeSelectorTerms: 
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - 123-worker 
        service:
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https